language: generic

env:
  - PYTHON_VERSION=3.5
  - PYTHON_VERSION=3.6
os:
  - linux
  - osx

branches:
only:
  - dev
  - master

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      curl -o miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
    fi

  # More conda setup to get miniconda in and a virtual env. setup
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels usgs-astrogeology
  - conda config --add channels conda-forge
  - conda update conda
  - conda info -a   # Useful for debugging any issues with conda
  - conda install pyhat
  # Create the env using the environment.yml
  - conda env create -n pyhat-env -f environment.yml
  - source activate pyhat-env

install:
  # Install dependencies
  - conda install pip setuptools
  # Development installation
  - conda install pytest pytest-cov nbsphinx
  - pip install coveralls travis-sphinx

script:
  - pytest --cov=libpyhat

after_success:
  # Code Coverage
  - coveralls
  # Anaconda Upload
  - source deactivate
  - conda install conda-build anaconda-client
  - conda config --set anaconda_upload yes
  - conda build --token $CONDA_UPLOAD_TOKEN --python $PYTHON_VERSION .
  # Docs to gh-pages
  - source activate pyhat-env  # Reactivate the env to have all deps installed.
  - travis-sphinx build --source=docs --nowarn # The sphinx build script
  - travis-sphinx deploy --branches=dev
